/**
 * GraphQL TypeScript Generator - Type Generator
 * Core logic for transforming GraphQL schema to TypeScript types
 */

import {
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLInterfaceType,
  GraphQLUnionType,
  GraphQLEnumType,
  GraphQLInputObjectType,
  GraphQLList,
  GraphQLNonNull,
  GraphQLNamedType,
  GraphQLOutputType,
  GraphQLInputType,
  GraphQLArgument
} from 'graphql';
import { formatDescription, isBuiltInScalar } from './utils';
import { join } from 'path';

export interface GeneratorOptions {
  namespace?: string;
  prefix?: string;
  skipEnums?: boolean;
  skipUnions?: boolean;
  schemaName?: string;
}

export interface GeneratedFile {
  filename: string;
  content: string;
}

/**
 * Main generator class
 */
export class TypeGenerator {
  private schema: GraphQLSchema;
  private options: GeneratorOptions;
  private generatedTypes: Set<string> = new Set();
  private outputLines: string[] = [];

  constructor(schema: GraphQLSchema, options: GeneratorOptions = {}) {
    this.schema = schema;
    this.options = {
      skipEnums: false,
      skipUnions: false,
      ...options
    };
  }

  /**
   * Generate all TypeScript types from schema
   */
  generate(): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    this.outputLines = [];
    this.generatedTypes = new Set();
    this.addHeader();

    // Generate enums first (they're referenced by other types)
    if (!this.options.skipEnums) {
      this.generateEnums();
    }

    // Generate interfaces for object types
    this.generateObjectTypes();

    // Generate input types
    this.generateInputTypes();

    // Generate unions
    if (!this.options.skipUnions) {
      this.generateUnions();
    }

    files.push({
      filename: this.getOutputFilename(),
      content: this.outputLines.join('\n')
    });

    return files;
  }

  /**
   * Add file header
   */
  private addHeader(): void {
    this.outputLines.push(`/**
 * Auto-generated TypeScript types from GraphQL schema
 * Generated by graphql-ts-generator
 * Caution: Manual edits may be overwritten
 */
`);
  }

  /**
   * Generate enum types
   */
  private generateEnums(): void {
    const typeMap = this.schema.getTypeMap();

    for (const typeName in typeMap) {
      const type = typeMap[typeName];

      if (type instanceof GraphQLEnumType && !typeName.startsWith('__')) {
        this.generateEnum(type);
      }
    }
  }

  /**
   * Generate a single enum
   */
  private generateEnum(type: GraphQLEnumType): void {
    const enumName = this.prefixName(type.name);

    if (type.description) {
      this.outputLines.push(formatDescription(type.description));
    }
    this.outputLines.push(`export enum ${enumName} {`);

    type.getValues().forEach(value => {
      this.outputLines.push(`  ${value.name} = ${JSON.stringify(value.value)},`);
    });

    this.outputLines.push(`}\n`);
    this.generatedTypes.add(enumName);
  }

  /**
   * Generate object and interface types (skipping Query/Mutation/Subscription root types
   * since they contain field arguments that don't map cleanly to interfaces)
   */
  private generateObjectTypes(): void {
    const typeMap = this.schema.getTypeMap();
    const queryType = this.schema.getQueryType();
    const mutationType = this.schema.getMutationType();
    const subscriptionType = this.schema.getSubscriptionType();

    for (const typeName in typeMap) {
      const type = typeMap[typeName];

      // Skip enums, unions, input types, and internal types
      if (
        type instanceof GraphQLEnumType ||
        type instanceof GraphQLUnionType ||
        type instanceof GraphQLInputObjectType ||
        typeName.startsWith('__')
      ) {
        continue;
      }

      if (type instanceof GraphQLObjectType || type instanceof GraphQLInterfaceType) {
        this.generateObjectType(type);
      }
    }
  }

  /**
   * Generate a single object or interface type
   */
  private generateObjectType(type: GraphQLObjectType | GraphQLInterfaceType): void {
    const typeName = this.prefixName(type.name);

    if (type.description) {
      this.outputLines.push(formatDescription(type.description));
    }
    this.outputLines.push(`export interface ${typeName} {`);

    const fields = type.getFields();

    for (const fieldName in fields) {
      const field = fields[fieldName];
      const fieldType = this.typeToString(field.type);

      if (field.description) {
        this.outputLines.push(`  ${formatDescription(field.description)}`);
      }

      this.outputLines.push(`  ${fieldName}: ${fieldType};`);
    }

    this.outputLines.push(`}\n`);
    this.generatedTypes.add(typeName);
  }

  /**
   * Convert GraphQL type to TypeScript type string.
   * Properly handles nested NonNull and List wrappers.
   *
   * GraphQL wrapping examples:
   *   String       → string | null
   *   String!      → string
   *   [String]     → (string | null)[] | null
   *   [String!]    → string[] | null
   *   [String!]!   → string[]
   *   [String]!    → (string | null)[]
   */
  typeToString(graphqlType: GraphQLOutputType | GraphQLInputType): string {
    return this.convertType(graphqlType);
  }

  private convertType(type: GraphQLOutputType | GraphQLInputType): string {
    if (type instanceof GraphQLNonNull) {
      return this.convertInner(type.ofType);
    }
    // Nullable at this level
    const inner = this.convertInner(type);
    return `${inner} | null`;
  }

  private convertInner(type: GraphQLOutputType | GraphQLInputType): string {
    if (type instanceof GraphQLNonNull) {
      return this.convertInner(type.ofType);
    }
    if (type instanceof GraphQLList) {
      const elementType = this.convertType(type.ofType);
      // Wrap complex element types in parens for clarity
      if (elementType.includes(' | ')) {
        return `(${elementType})[]`;
      }
      return `${elementType}[]`;
    }
    // Named type
    return this.namedTypeToString((type as GraphQLNamedType).name);
  }

  private namedTypeToString(typeName: string): string {
    if (isBuiltInScalar(typeName)) {
      const scalarMap: Record<string, string> = {
        'Int': 'number',
        'Float': 'number',
        'String': 'string',
        'Boolean': 'boolean',
        'ID': 'string'
      };
      return scalarMap[typeName] || 'any';
    }
    // Custom scalar or named type
    return this.prefixName(typeName);
  }

  /**
   * Generate input object types
   */
  private generateInputTypes(): void {
    const typeMap = this.schema.getTypeMap();

    for (const typeName in typeMap) {
      const type = typeMap[typeName];

      if (type instanceof GraphQLInputObjectType && !typeName.startsWith('__')) {
        this.generateInputType(type);
      }
    }
  }

  /**
   * Generate a single input type
   */
  private generateInputType(type: GraphQLInputObjectType): void {
    const typeName = this.prefixName(type.name);

    if (type.description) {
      this.outputLines.push(formatDescription(type.description));
    }
    this.outputLines.push(`export interface ${typeName} {`);

    const fields = type.getFields();

    for (const fieldName in fields) {
      const field = fields[fieldName];
      const fieldType = this.typeToString(field.type);

      if (field.description) {
        this.outputLines.push(`  ${formatDescription(field.description)}`);
      }

      // If field has a default value, it's optional in TS
      const isOptional = field.defaultValue !== undefined;
      this.outputLines.push(`  ${fieldName}${isOptional ? '?' : ''}: ${fieldType};`);
    }

    this.outputLines.push(`}\n`);
    this.generatedTypes.add(typeName);
  }

  /**
   * Generate union types
   */
  private generateUnions(): void {
    const typeMap = this.schema.getTypeMap();

    for (const typeName in typeMap) {
      const type = typeMap[typeName];

      if (type instanceof GraphQLUnionType && !typeName.startsWith('__')) {
        this.generateUnion(type);
      }
    }
  }

  /**
   * Generate a single union type
   */
  private generateUnion(type: GraphQLUnionType): void {
    const unionName = this.prefixName(type.name);
    const memberTypes = type.getTypes().map(t => this.prefixName(t.name));

    if (type.description) {
      this.outputLines.push(formatDescription(type.description));
    }
    this.outputLines.push(`export type ${unionName} = ${memberTypes.join(' | ')};\n`);
    this.generatedTypes.add(unionName);
  }

  /**
   * Apply prefix to a type name
   */
  private prefixName(name: string): string {
    return this.options.prefix ? `${this.options.prefix}${name}` : name;
  }

  /**
   * Get output filename
   */
  private getOutputFilename(): string {
    const schemaName = this.options.schemaName || 'types';
    const prefix = this.options.prefix ? `${this.options.prefix}_` : '';
    return `${prefix}${schemaName}.generated.ts`;
  }
}

/**
 * Get output directory for generated files
 */
export function getOutputDir(outputPath: string): string {
  if (!outputPath.startsWith('/') && !outputPath.match(/^[a-zA-Z]:\\/)) {
    return join(process.cwd(), outputPath);
  }
  return outputPath;
}
